// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhyk0OKUzFfZ7kRXB_aqoS-WxvIUTGz9o',
    appId: '1:291058064540:web:072b96a8494bc6bd00a159',
    messagingSenderId: '291058064540',
    projectId: 'gaviotabackend',
    authDomain: 'gaviotabackend.firebaseapp.com',
    storageBucket: 'gaviotabackend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA66nDfTxGe33-JlV-_ClpLqxjKEddjqas',
    appId: '1:291058064540:android:cdc3752253c6a73500a159',
    messagingSenderId: '291058064540',
    projectId: 'gaviotabackend',
    storageBucket: 'gaviotabackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7yxRG_U9XEKHO5WgKAMgLeEtS06IjGHE',
    appId: '1:291058064540:ios:b7953c79208bd49c00a159',
    messagingSenderId: '291058064540',
    projectId: 'gaviotabackend',
    storageBucket: 'gaviotabackend.appspot.com',
    iosClientId: '291058064540-khhsttr1lmpmg0j5fhtcea1d8bltigi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gaviotaApp',
  );
}
